<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MedGrupo_teste.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedGrupo-teste.Domain\MedGrupo-teste.Domain.csproj" />
  </ItemGroup>

</Project>
